#!/bin/sh
#
# Start the MSD gadget
#

case "$1" in
start)

printf "Starting MSD: "
/usr/local/bin/configure-gadgets
[ $? = 0 ] && echo "OK" || echo "FAIL"
;;
stop)
[ $? = 0 ] && echo "OK" || echo "FAIL"
;;
restart|reload)
"$0" stop
"$0" start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac

exit $?

